In [2]:
import numpy as np

In [119]:
from numpy import random

In [3]:
print(np.__version__)

1.23.2


In [4]:
# NumPy is a Python library used for working with arrays.

# It also has functions for working in domain of linear algebra, fourier transform, and matrices.

# NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

# NumPy stands for Numerical Python.

# Why Use NumPy?
# In Python we have lists that serve the purpose of arrays, but they are slow to process.

# NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

# The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

# NumPy is used to work with arrays. The array object in NumPy is called ndarray.
# We can create a NumPy ndarray object by using the array() function.
# To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:

In [5]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

print()

arr = np.array((1,2,3,4,5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
# Arrays can have as many number of dimensions starting from zero dimension(0-D) and ndim is used to check number of dimensions
# An array that has 2-D arrays (matrices) as its elements is called 3-D array.

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
e = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
f = np.array([[[1, 2, 3], [4, 5, 6]]])


print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
print(e.ndim)
print(f.ndim)


0
1
2
3
3
3


In [7]:
# When the array is created, you can define the number of dimensions by using the ndmin argument.
arrr = np.array([[1,2,3], [4,5,6]], ndmin=3)
print(arrr)
print('number of dimensions: ', arrr.ndim)

[[[1 2 3]
  [4 5 6]]]
number of dimensions:  3


In [8]:
# Array indexing is the same as accessing an array element.
# You can access an array element by referring to its index number.
# The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

arr = np.array([1,2,3,4,5])
print(arr[0])

print()

print(arr[2] + arr[3])

1

7


In [9]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [10]:
arr = np.array([[[1,2,3,4,5], [6,7,8,9,10]]])

print('2nd element on 1st row: ', arr[0, 0, 1])

2nd element on 1st row:  2


In [11]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])

# arr[0, 1, 2] prints the value 6.

# And this is why:

# The first number represents the first dimension, which contains two arrays:
# [[1, 2, 3], [4, 5, 6]]
# and:
# [[7, 8, 9], [10, 11, 12]]
# Since we selected 0, we are left with the first array:
# [[1, 2, 3], [4, 5, 6]]

# The second number represents the second dimension, which also contains two arrays:
# [1, 2, 3]
# and:
# [4, 5, 6]
# Since we selected 1, we are left with the second array:
# [4, 5, 6]

# The third number represents the third dimension, which contains three values:
# 4
# 5
# 6
# Since we selected 2, we end up with the third value:
# 6



6


In [12]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [13]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

print()

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[4:])

print()

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[:4])

[2 3 4 5]

[5 6 7]

[1 2 3 4]


In [23]:
# negative slicing
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-3:-1])

print()

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])

print()

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])


[5 6]

[2 4]

[7 8 9]


In [24]:
# Data Types in Python

# strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"
# integer - used to represent integer numbers. e.g. -1, -2, -3
# float - used to represent real numbers. e.g. 1.2, 42.42
# boolean - used to represent True or False.
# complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j

# Data Types in NumPy
# NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

# Below is a list of all data types in NumPy and the characters used to represent them.

# i - integer
# b - boolean
# u - unsigned integer
# f - float
# c - complex float
# m - timedelta
# M - datetime
# O - object
# S - string
# U - unicode string
# V - fixed chunk of memory for other type ( void )

In [31]:
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

print()

arr = np.array(['apple', 'carrot', 'banana', 'corn'])
print(arr.dtype)

print()

arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)

print()

arr = np.array([1, 2, 3, 4], dtype='i4')
print(arr)
print(arr.dtype)



int32

<U6

[b'1' b'2' b'3' b'4']
|S1

[1 2 3 4]
int32


In [37]:
# The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.
# The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.
# The data type can be specified using a string, like 'f' for float, 'i' for integer etc. 
# or you can use the data type directly like float for float and int for integer.

arr = np.array([1.1, 2.2, 3.8, 4.5])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

print()

arr = np.array([1.1, 2.2, 3.8, 4.5, 0.0])
newarr = arr.astype(int)
print(newarr)
print(newarr.dtype)

print()

newarr1 = newarr.astype(bool)
print(newarr1)
print(newarr1.dtype)

[1 2 3 4]
int32

[1 2 3 4 0]
int32

[ True  True  True  True False]
bool


In [39]:
# The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.
# The copy owns the data and any changes made to the copy will not affect original array, 
# and any changes made to the original array will not affect the copy.
# The view does not own the data and any changes made to the view will affect the original array, 
# and any changes made to the original array will affect the view.

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

print()

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]

[42  2  3  4  5]
[42  2  3  4  5]


In [41]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 54

print(arr)
print(x)

print()

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
x[0] = 54

print(arr)
print(x)

[54  2  3  4  5]
[54  2  3  4  5]

[1 2 3 4 5]
[54  2  3  4  5]


In [42]:
# As mentioned above, copies owns the data, and views does not own the data, but how can we check this?
# Every NumPy array has the attribute base that returns None if the array owns the data.
# Otherwise, the base  attribute refers to the original object.

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [45]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

# the result (2,4) means it is a 2 dimension array with four elements in each of them

print()

# arr = np.array([[1, 2, 3], [5, 6, 7, 8]])
# print(arr.shape)

arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('shape of array :', arr.shape)

(2, 4)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [47]:
# Reshaping arrays
# Reshaping means changing the shape of an array.
# The shape of an array is the number of elements in each dimension.
# By reshaping we can add or remove dimensions or change number of elements in each dimension

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

print()

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(3, 4)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [56]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)   # it will have 2 arrays plus 3 arrays plus 2 elements that makes up the 3 arrays
print(newarr)
print(newarr.ndim)

print()

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr.reshape(2, 4).base)

print()

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 2, -1)
print(newarr)
# The original array has 8 elements.
# reshape(2, 2, -1) means:
# First dimension: 2
# Second dimension: 2
# Third dimension: NumPy calculates it as 8 / (2 * 2) = 2
# So, the resulting shape will be (2, 2, 2).

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 2, -1)
print(newarr)

print()

# to convert a multidimensional array to 1-D we use .reshape(-1)
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3

[1 2 3 4 5 6 7 8]

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

[1 2 3 4 5 6]


In [66]:
# to iterate numpy arrays we use 'for' loop

arr = np.array([1, 2, 3, 4, 5, 6])
for x in arr:
  print(x)

print()

arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
  print(x)

print()

arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
  for y in x:
    print(y)

print()

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
  print(x)

print()

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6

[1 2 3]
[4 5 6]

1
2
3
4
5
6

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]

1
2
3
4
5
6
7
8
9
10
11
12
7
8
9
10
11
12


In [69]:
# .nditer gives the full results without having to go through the stress of for x, for y, for z,...
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr):
  print(x)

print()

arr = np.array([1, 2, 3])
for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

print()

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for x in np.nditer(arr[:, ::2]):
  print(x)

1
2
3
4
5
6
7
8

b'1'
b'2'
b'3'

1
3
5
7


In [ ]:
# to get the order of each element in the array we use .ndenumerate
arr = np.array([1, 2, 3])
for idx, x in np.ndenumerate(arr):
  print(idx, x)

print()

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [74]:
# to join arrays we use .concatenate function like as of python or excel
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9])
arr = np.concatenate((arr1, arr2, arr3))
print(arr)

print()

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[1 2 3 4 5 6 7 8 9]

[[1 2 5 6]
 [3 4 7 8]]


In [75]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [76]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [77]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [82]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([4, 5, 6])
arr = np.dstack((arr1, arr2, arr3))
print(arr)


[[[1 4 4]
  [2 5 5]
  [3 6 6]]]


In [79]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [87]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
newarr = np.array_split(arr, 4)
print(newarr)

print()

arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr[0])
print(newarr[1])
print(newarr[2])

[array([1, 2]), array([3, 4]), array([5, 6]), array([7])]

[1 2]
[3 4]
[5 6]


In [90]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)
print(newarr)

print()

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.hsplit(arr, 3)
print(newarr)

print()

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.array_split(arr, 3, axis=1)
print(newarr)


[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [93]:
# to search an array we use the ,where method
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)

# the result means that the value 4 is present at index 3, 5, and 6.

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 0)
print(x)

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 1)
print(x)

(array([3, 5, 6], dtype=int64),)
(array([1, 3, 5, 7], dtype=int64),)
(array([0, 2, 4, 6], dtype=int64),)


In [108]:
# There is a method called searchsorted() which performs a binary search in the array, 
# and returns the index where the specified value would be inserted to maintain the search order.
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7)
print(x)

arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 5)
print(x)

# The number 7 should be inserted on index 1 to remain the sort order.
# The method starts the search from the left and returns the first index where the number 7 is no longer larger than the next value.

print()

# By default the left most index is returned, but we can give side='right' to return the right most index instead.
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 8)#side='right')
print(x)

arr = np.array([1, 3, 5, 7])
x = np.searchsorted(arr, [4, 6, 8])
print(x)


1
0

2
[2 3 4]


In [114]:
# Sorting means putting elements in an ordered sequence.
# we use ,sort to sort in munpy
arr = np.array([3, 5, 2, 0])
print(np.sort(arr))

arr = np.array(['banana', 'cherry', 'apple', 'zeal', 'mango'])
print(np.sort(arr))

arr = np.array([True, False, True, True, False])
print(np.sort(arr))

arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))


[0 2 3 5]
['apple' 'banana' 'cherry' 'mango' 'zeal']
[False False  True  True  True]
[[2 3 4]
 [0 1 5]]


In [115]:
import numpy as np

arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [116]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]


In [118]:
arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

print()

arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]

[False  True False  True False  True False]
[2 4 6]


In [121]:
# to generate a random integer from 0 to 100
x = random.randint(100)
print(x)

59
