In [2]:
import numpy as np

In [3]:
print(np.__version__)

1.23.2


In [4]:
# NumPy is a Python library used for working with arrays.

# It also has functions for working in domain of linear algebra, fourier transform, and matrices.

# NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

# NumPy stands for Numerical Python.

# Why Use NumPy?
# In Python we have lists that serve the purpose of arrays, but they are slow to process.

# NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

# The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

# NumPy is used to work with arrays. The array object in NumPy is called ndarray.
# We can create a NumPy ndarray object by using the array() function.
# To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:

In [5]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

print()

arr = np.array((1,2,3,4,5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
# Arrays can have as many number of dimensions starting from zero dimension(0-D) and ndim is used to check number of dimensions
# An array that has 2-D arrays (matrices) as its elements is called 3-D array.

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
e = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
f = np.array([[[1, 2, 3], [4, 5, 6]]])


print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
print(e.ndim)
print(f.ndim)


0
1
2
3
3
3


In [7]:
# When the array is created, you can define the number of dimensions by using the ndmin argument.
arrr = np.array([[1,2,3], [4,5,6]], ndmin=3)
print(arrr)
print('number of dimensions: ', arrr.ndim)

[[[1 2 3]
  [4 5 6]]]
number of dimensions:  3


In [8]:
# Array indexing is the same as accessing an array element.
# You can access an array element by referring to its index number.
# The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

arr = np.array([1,2,3,4,5])
print(arr[0])

print()

print(arr[2] + arr[3])

1

7


In [9]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [10]:
arr = np.array([[[1,2,3,4,5], [6,7,8,9,10]]])

print('2nd element on 1st row: ', arr[0, 0, 1])

2nd element on 1st row:  2


In [11]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])

# arr[0, 1, 2] prints the value 6.

# And this is why:

# The first number represents the first dimension, which contains two arrays:
# [[1, 2, 3], [4, 5, 6]]
# and:
# [[7, 8, 9], [10, 11, 12]]
# Since we selected 0, we are left with the first array:
# [[1, 2, 3], [4, 5, 6]]

# The second number represents the second dimension, which also contains two arrays:
# [1, 2, 3]
# and:
# [4, 5, 6]
# Since we selected 1, we are left with the second array:
# [4, 5, 6]

# The third number represents the third dimension, which contains three values:
# 4
# 5
# 6
# Since we selected 2, we end up with the third value:
# 6



6


In [12]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [13]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

print()

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[4:])

print()

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[:4])

[2 3 4 5]

[5 6 7]

[1 2 3 4]


In [23]:
# negative slicing
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-3:-1])

print()

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])

print()

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])


[5 6]

[2 4]

[7 8 9]


In [24]:
# Data Types in Python

# strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"
# integer - used to represent integer numbers. e.g. -1, -2, -3
# float - used to represent real numbers. e.g. 1.2, 42.42
# boolean - used to represent True or False.
# complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j

# Data Types in NumPy
# NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

# Below is a list of all data types in NumPy and the characters used to represent them.

# i - integer
# b - boolean
# u - unsigned integer
# f - float
# c - complex float
# m - timedelta
# M - datetime
# O - object
# S - string
# U - unicode string
# V - fixed chunk of memory for other type ( void )

In [31]:
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

print()

arr = np.array(['apple', 'carrot', 'banana', 'corn'])
print(arr.dtype)

print()

arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)

print()

arr = np.array([1, 2, 3, 4], dtype='i4')
print(arr)
print(arr.dtype)



int32

<U6

[b'1' b'2' b'3' b'4']
|S1

[1 2 3 4]
int32


In [37]:
# The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.
# The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.
# The data type can be specified using a string, like 'f' for float, 'i' for integer etc. 
# or you can use the data type directly like float for float and int for integer.

arr = np.array([1.1, 2.2, 3.8, 4.5])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

print()

arr = np.array([1.1, 2.2, 3.8, 4.5, 0.0])
newarr = arr.astype(int)
print(newarr)
print(newarr.dtype)

print()

newarr1 = newarr.astype(bool)
print(newarr1)
print(newarr1.dtype)

[1 2 3 4]
int32

[1 2 3 4 0]
int32

[ True  True  True  True False]
bool


In [39]:
# The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.
# The copy owns the data and any changes made to the copy will not affect original array, 
# and any changes made to the original array will not affect the copy.
# The view does not own the data and any changes made to the view will affect the original array, 
# and any changes made to the original array will affect the view.

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

print()

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]

[42  2  3  4  5]
[42  2  3  4  5]
