In [2]:
import numpy as np

In [6]:
print(np.__version__)

1.23.2


In [ ]:
# NumPy is a Python library used for working with arrays.

# It also has functions for working in domain of linear algebra, fourier transform, and matrices.

# NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

# NumPy stands for Numerical Python.

# Why Use NumPy?
# In Python we have lists that serve the purpose of arrays, but they are slow to process.

# NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

# The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

# NumPy is used to work with arrays. The array object in NumPy is called ndarray.
# We can create a NumPy ndarray object by using the array() function.
# To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:

In [7]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

print()

arr = np.array((1,2,3,4,5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [17]:
# Arrays can have as many number of dimensions starting from zero dimension(0-D) and ndim is used to check number of dimensions
# An array that has 2-D arrays (matrices) as its elements is called 3-D array.

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
e = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
f = np.array([[[1, 2, 3], [4, 5, 6]]])


print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
print(e.ndim)
print(f.ndim)


0
1
2
3
3
3


In [14]:
# When the array is created, you can define the number of dimensions by using the ndmin argument.
arrr = np.array([[1,2,3], [4,5,6]], ndmin=3)
print(arrr)
print('number of dimensions: ', arrr.ndim)

[[[1 2 3]
  [4 5 6]]]
number of dimensions:  3
